# Generated by Django 3.1.1 on 2020-09-30 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200929_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=56)),
                ('postcode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=56)),
                ('town', models.CharField(max_length=56)),
                ('street', models.CharField(max_length=128)),
                ('address_1', models.CharField(max_length=256)),
                ('address_2', models.CharField(max_length=256)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
