# Generated by Django 3.1.1 on 2020-10-12 05:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201010_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='json_order',
        ),
        migrations.AddField(
            model_name='order',
            name='json_orderitems',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingaddress',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d42bf71d-4bc4-4fa6-b599-079a1cc8e1ac'), editable=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
