# Generated by Django 3.1.1 on 2020-10-12 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201012_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='store.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('394d0956-0073-4d37-9e40-3bf40e4dfb8f'), editable=False),
        ),
    ]
