# Generated by Django 3.1.1 on 2020-10-12 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201012_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('86031e9b-50eb-4ff2-ba30-ceca54ce3c9a'), editable=False),
        ),
    ]
