# Generated by Django 3.1.1 on 2020-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201005_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margin',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
