# Generated by Django 3.1.1 on 2020-10-06 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201005_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FINISHED', 'FINISHED')], default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d22beeb-aecb-48dc-8a0f-a81f37784153')),
        ),
    ]
