# Generated by Django 3.1.1 on 2020-10-08 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201006_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a4146608-4a8c-4e89-9566-003b6e208b76')),
        ),
    ]
