# Generated by Django 3.1.1 on 2020-10-08 06:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201008_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='json_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3890f3b-0250-48be-a7f9-c3e451e99d46')),
        ),
    ]
