# Generated by Django 3.1.1 on 2020-10-12 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201012_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c97c92d4-7283-4de6-ab77-8f0c86ba169c'), editable=False),
        ),
    ]
