# Generated by Django 3.1.1 on 2020-10-12 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201012_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5a2c4e38-c584-4eb4-a29b-584e12240f3f'), editable=False),
        ),
    ]
