# Generated by Django 3.1.1 on 2020-10-12 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201012_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b2c60a43-9de1-4664-a47a-437975763d41'), editable=False),
        ),
    ]
