# Generated by Django 3.1.1 on 2020-10-12 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201012_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
