# Generated by Django 3.1.1 on 2020-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201014_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='margin',
            old_name='is_paid',
            new_name='is_refound',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
