# Generated by Django 3.1.1 on 2020-10-22 01:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='json_shippingaddress',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
