# Generated by Django 3.1.1 on 2020-10-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_json_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
