# Generated by Django 3.1.1 on 2020-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orderitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
