# Generated by Django 3.1.1 on 2020-10-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201022_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingaddress',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress'),
        ),
    ]
