# Generated by Django 3.1.1 on 2020-11-04 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_auto_20201028_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('targetNum', models.IntegerField(default=0)),
                ('currentNum', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('until_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='description', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.CreateModel(
            name='PingoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(default='new', max_length=28)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_info', models.TextField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingo_orders', to='store.pingoitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pingo_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
