# Generated by Django 3.1.1 on 2020-11-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_pingoitem_pingoorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingoitem',
            name='product',
        ),
        migrations.AddField(
            model_name='pingoitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pingo_items', to='store.item'),
            preserve_default=False,
        ),
    ]
