# Generated by Django 3.1.1 on 2020-11-29 13:51

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to=store.models.image_path),
        ),
    ]
