# Generated by Django 3.1.1 on 2020-11-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20201129_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file',
        ),
    ]
