version: '3.7'

services:
  nginx:
    build: ./system/nginx
    volumes:
      - ./exrate2020/staticfiles:/home/app/web/staticfiles
      - ./exrate2020/mediafiles:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

  web:
    container_name: web
#    build: ./exrate2020
    build:
      context: ./exrate2020
      dockerfile: Dockerfile.prod
    command: gunicorn exrate2020.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./exrate2020/:/home/app/web
      - ./exrate2020/staticfiles:/home/app/web/staticfiles
      - ./exrate2020/mediafiles:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    hostname: postgres
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./system/postgres/init.d:/docker-entrypoint-initdb.d
      - ./system/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lionhu
      POSTGRES_PASSWORD: lionhu
      POSTGRES_DB: exrate
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 8060:80
    volumes:
      - ./system/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    restart: always

  redis:
    container_name: redis
    restart: always
    tty: true
    build:
      context: ./system/redis
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
    volumes:
      - ./system/redis/redis_data:/var/redis
      - ./system/redis/conf/6379.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes

  redis-commander:
      container_name: redis_commander
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=Hisshghu3500
      ports:
        - 8081:8081
      depends_on:
        - redis

  vue_app:
    container_name: vue_app
    build:
      context: ./exrate2020/vueapp
    ports:
      - 9050:8080
    volumes:
      - ./exrate2020/vueapp/vue_django:/usr/src/app/
    stdin_open: true
    tty: true
    command: ["npm", "run", "serve"]


volumes:
  static_volume:
  media_volume: