version: '3.7'

services:
  web:
    hostname: web
    build: ./exrate2020
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./exrate2020/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    hostname: postgres
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./system/postgres/init.d:/docker-entrypoint-initdb.d
      - ./system/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lionhu
      POSTGRES_PASSWORD: lionhu
      POSTGRES_DB : exrate
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 8060:80
    volumes:
      - ./system/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    restart: always