version: '3.2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - "nginx-proxy"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=csr@nichiei.services

  nginx:
    build: ./system/nginx
    hostname: nginx
    container_name: nginx
    volumes:
      - ./exrate2020/staticfiles:/home/app/web/staticfiles
      - ./exrate2020/mediafiles:/home/app/web/mediafiles
      - ./exrate2020/logs/nginx:/var/log/nginx
      - ./system/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
#    ports:
#      - 80:80
    environment:
      - VIRTUAL_HOST=www.nichiei.services
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.nichiei.services
      - LETSENCRYPT_EMAIL=csr@nichiei.services
    depends_on:
      - web

  web:
    container_name: web
#    build: ./exrate2020
    build:
      context: ./exrate2020
      dockerfile: Dockerfile.prod
#    command: gunicorn exrate2020.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./exrate2020/:/home/app/web
      - ./exrate2020/staticfiles:/home/app/web/staticfiles
      - ./exrate2020/mediafiles:/home/app/web/mediafiles
      - ./exrate2020/logs:/etc/supervisor/logs
      - ./exrate2020/system/certs:/etc/nginx/certs
      - ./exrate2020/system/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./system/fonts:/usr/share/fonts
    expose:
      - 8000
#      - 8001
    ports:
      - 8001:8001
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    hostname: postgres
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./system/postgres/init.d:/docker-entrypoint-initdb.d
      - ./system/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lionhu
      POSTGRES_PASSWORD: lionhu
      POSTGRES_DB: exrate
      PGTZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root

  pgadmin4:
    hostname: pgadmin4
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 8060:80
    volumes:
      - ./system/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - postgres
    restart: always

  redis:
    container_name: redis
    restart: always
    tty: true
    build:
      context: ./system/redis
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
    volumes:
      - ./system/redis/redis_data:/var/redis
      - ./system/redis/conf/6379.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes

  redis-commander:
      container_name: redis_commander
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=root
        - HTTP_PASSWORD=Hisshghu3500
      ports:
        - 8081:8081
      depends_on:
        - redis

#  vue_app:
#    container_name: vue_app
#    build:
#      context: ./exrate2020/vueapp
#    ports:
#      - 9050:8080
#    volumes:
#      - ./exrate2020/vueapp/vue_django:/usr/src/app/
#    stdin_open: true
#    tty: true
#    command: ["npm", "run", "serve"]

  rabbitmq:
    container_name: rabbitmq
    image:  rabbitmq:3.7.3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: my_vhost
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  certs:
  html:
  vhost:
  dhparam:
