# Generated by Django 3.1.1 on 2020-10-05 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('45116b49-c9f3-4b44-a9b6-05544190b18a')),
        ),
    ]
