# Generated by Django 3.1.1 on 2020-10-05 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201005_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('73f856c8-2f70-4655-bfb1-a07e04d45fe2')),
        ),
    ]
