# Generated by Django 3.1.1 on 2020-10-10 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201010_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('09430654-2df6-4995-b3bd-efd7971b884f')),
        ),
    ]
