# Generated by Django 3.1.1 on 2020-09-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200911_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=255, unique=True),
        ),
    ]
