# Generated by Django 3.1.1 on 2020-10-12 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201010_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('10ae7572-a696-4ff1-aeee-3fc7383a5a0a')),
        ),
    ]
