# Generated by Django 3.1.1 on 2020-09-15 14:46

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=authentication.models.user_avatar_path),
        ),
    ]
