# Generated by Django 3.1.1 on 2020-10-05 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201005_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('f10e4aa5-a1e9-4a83-ab9c-90bda10e0999')),
        ),
    ]
