# Generated by Django 3.1.1 on 2020-10-05 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201005_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('a71625b9-adb9-4496-b156-d3c8c0eda2bb')),
        ),
    ]
