# Generated by Django 3.1.1 on 2020-10-12 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20201012_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('a87741a1-b101-439c-8bcd-83d32c4591bc')),
        ),
    ]
