# Generated by Django 3.1.1 on 2020-10-08 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201006_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('62ecc987-1a9b-480d-8046-f33279226d36')),
        ),
    ]
