# Generated by Django 3.1.1 on 2020-10-12 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201012_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('058157e8-6210-494b-b56b-98b66c27da1e')),
        ),
    ]
