# Generated by Django 3.1.1 on 2020-10-08 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201008_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('12d22e13-c9d2-4cc9-a50d-52ad7b5d7d00')),
        ),
    ]
