# Generated by Django 3.1.1 on 2020-10-12 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201012_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('1ab3be82-0b60-4a60-a2ea-c5acb03060e9')),
        ),
    ]
