# Generated by Django 3.1.1 on 2020-10-12 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20201012_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('72a49239-f276-4506-8fb4-22102592952d')),
        ),
    ]
