# Generated by Django 3.1.1 on 2020-10-12 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201012_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('52e03453-b8c0-4f36-a229-81af437e2600')),
        ),
    ]
