# Generated by Django 3.1.1 on 2020-10-12 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20201012_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('9a36b22c-18c0-4850-b525-aa9a4bd12f21')),
        ),
    ]
