# Generated by Django 3.1.1 on 2020-10-12 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20201012_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('8af607f7-3b56-48ca-bec3-8e8cd4e8a426')),
        ),
    ]
