# Generated by Django 3.1.1 on 2020-10-14 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20201012_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('8246e571-69cb-40b4-8747-c345975f7a6e')),
        ),
    ]
