# Generated by Django 3.1.1 on 2020-10-17 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20201014_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('3c4c06c5-ed8d-4996-9b67-a11f9741d199')),
        ),
    ]
