# Generated by Django 3.1.1 on 2020-10-22 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20201020_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('06893e7a-a90e-43fb-99f5-64a799eafe91')),
        ),
    ]
