# Generated by Django 3.1.1 on 2020-10-22 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20201022_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('6fb76a91-6d9c-4347-ad2d-97a10dc74a1e')),
        ),
    ]
