# Generated by Django 3.1.1 on 2020-10-22 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20201022_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('703f0c0a-5b42-40b6-80de-839e9dc8a831')),
        ),
    ]
