# Generated by Django 3.1.1 on 2020-10-28 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20201022_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('e96dda90-e114-4d45-8629-ee1fbe147d39')),
        ),
    ]
