# Generated by Django 3.1.1 on 2020-11-04 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20201028_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('59e32f14-74e2-4542-a283-03bb2ce8c9f9')),
        ),
    ]
