# Generated by Django 3.1.1 on 2020-11-04 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20201104_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('1097736f-e2f5-4e54-b293-e7177f7b57ce')),
        ),
    ]
