# Generated by Django 3.1.1 on 2020-11-10 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20201104_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('75594040-06ee-4ed3-bcba-8d52367b2458')),
        ),
    ]
