# Generated by Django 3.1.1 on 2020-11-25 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_auto_20201125_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('29417151-a330-483d-a020-f65a2fa527d0')),
        ),
    ]
