# Generated by Django 3.1.1 on 2020-11-29 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20201128_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introcode',
            field=models.UUIDField(default=uuid.UUID('596b5e5d-3b3b-48df-98d7-ff2d2ef950d7')),
        ),
    ]
