# Generated by Django 3.1.1 on 2020-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studydjango', '0002_auto_20200924_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
